/*
Author:
 Luis Fuentes Auraad
 Autómata Industrial
 Back-end Developer
 Cel: 3004386841
 */ 
package Form;

import Modelo.Reloj;
import java.awt.Image;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;


public class Recomendaciones extends javax.swing.JFrame implements Runnable{

    private javax.swing.JFrame inicioForm;
    Reloj reloj = new Reloj();
    Thread hilo;
    /*FileInputStream direccion;
    AudioStream audio;*/
    
    public Recomendaciones() throws FileNotFoundException, IOException {
        initComponents();
        /*this.direccion = new FileInputStream("F:\\PROYECTOS\\Psicología\\Audio\\Principal.wav");
        this.audio = new AudioStream(direccion);        
        AudioPlayer.player.start(audio);*/
        hilo = new Thread(this);
        hilo.start();
        fechaLB.setText(reloj.fechaActual());
        setResizable(false);
        this.setLocationRelativeTo(null);
        Image icon = new ImageIcon(getClass()
                .getResource("/Imagenes/recomendar.png")).getImage();
        setIconImage(icon);
        this.setTitle("Recomendaciones");
        
        estres_txPane.setText("MANEJO DEL ESTRÉS LABORAL\n\n" +
"°Administre los factores estresantes que contribuyen al agotamiento del "
                + "trabajo. Una vez que haya identificado lo que está "
                + "alimentando sus síntomas de Burnout, puede hacer un plan para"
                + " resolver los problemas.\n\n" +
"°Evalúe sus opciones. Discuta las preocupaciones específicas con su supervisor."
                + " Tal vez puedan trabajar juntos para cambiar las expectativas"
                + " o llegar a compromisos o soluciones.\n\n" +
"°Ajuste su actitud. Si se ha vuelto cínico en el trabajo, tenga en cuenta las "
                + "formas de mejorar su perspectiva. Vuelva a descubrir los "
                + "aspectos agradables de su puesto. Establezca relaciones "
                + "positivas con los compañeros para lograr mejores resultados. "
                + "Tome descansos cortos durante todo el día. Pase tiempo fuera "
                + "de la oficina y haga las cosas que le gustan.\n\n" +
"°Busque apoyo. Ya sea que llegue a los compañeros de trabajo, amigos, seres "
                + "queridos u otras personas, el apoyo y la colaboración pueden "
                + "ayudar a lidiar con el estrés laboral y la sensación de "
                + "agotamiento. Si usted tiene acceso a un programa de "
                + "asistencia al empleado, aproveche los servicios disponibles.\n\n" +
"°Evalúe sus intereses, habilidades y pasiones. Una evaluación honesta puede "
                + "ayudarle a decidir si debe considerar un trabajo alternativo,"
                + " como por ejemplo uno que es menos exigente o que mejor se "
                + "ajusta a sus intereses o valores fundamentales.\n\n" +
"°Haga algo de ejercicio. La actividad física regular como caminar o andar en "
                + "bicicleta, puede ayudarle a lidiar mejor con el estrés. "
                + "También puede ayudarle a desconectar fuera del trabajo y "
                + "dedicarse a otra cosa.\n\n" +
"°Comunícate: Sé amable, expón la situación y procura no enfadarte, no tienes "
                + "nada que perder y mucho por ganar. \n\n" +
"En resumen, lo recomendable es mantener una mente abierta mientras considera "
                + "las opciones, y si piensa que está sufriendo este síndrome, "
                + "intente solucionarlo lo antes posible. \n\n" +
"También es importante de no hacer del problema algo más grave confundiendo el "
                + "Síndrome Burnout con una enfermedad: ni lo es, ni sus "
                + "desencadenantes tienen por qué encontrarse en el cuerpo de "
                + "uno mismo para tener claro esto, es bueno leer este artículo:"
                + " \"Las diferencias entre síndrome, trastorno y enfermedad");      
}
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fechaLB = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        horaLB = new javax.swing.JLabel();
        tags = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        estres_txPane = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        video2_button = new javax.swing.JButton();
        video3_button = new javax.swing.JButton();
        video4_button = new javax.swing.JButton();
        video1_button = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        video5_button = new javax.swing.JButton();
        home_button = new javax.swing.JButton();
        audio_ok = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono_Coachandling_v1.4.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel7.setText("COACHANDLIG");

        jLabel8.setFont(new java.awt.Font("Muli", 0, 8)); // NOI18N
        jLabel8.setText("BURNOUT  S.A");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendario_.png"))); // NOI18N

        fechaLB.setFont(new java.awt.Font("ABeeZee", 0, 14)); // NOI18N
        fechaLB.setText("Fecha");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reloj_.png"))); // NOI18N

        horaLB.setFont(new java.awt.Font("ABeeZee", 0, 14)); // NOI18N
        horaLB.setText("hora");

        tags.setFont(new java.awt.Font("Muli", 1, 14)); // NOI18N

        estres_txPane.setEditable(false);
        estres_txPane.setBackground(new java.awt.Color(151, 222, 151));
        estres_txPane.setFont(new java.awt.Font("ABeeZee", 0, 20)); // NOI18N
        estres_txPane.setAutoscrolls(false);
        jScrollPane1.setViewportView(estres_txPane);

        tags.addTab("MANEJO DEL ESTRÉS LABORAL", jScrollPane1);

        jPanel3.setBackground(new java.awt.Color(151, 222, 151));

        jLabel2.setFont(new java.awt.Font("Muli", 0, 18)); // NOI18N
        jLabel2.setText("4 Trucos para dormir toda la noche como un bebé");

        jLabel3.setFont(new java.awt.Font("Muli", 0, 18)); // NOI18N
        jLabel3.setText("Manejo del estrés laboral");

        jLabel4.setFont(new java.awt.Font("Muli", 0, 18)); // NOI18N
        jLabel4.setText("Qué es el síndrome de Burnout");

        jLabel9.setFont(new java.awt.Font("Muli", 0, 18)); // NOI18N
        jLabel9.setText("5 Ejercicios para olvidarte de los problemas de espalda");

        video2_button.setFont(new java.awt.Font("Merienda One", 0, 18)); // NOI18N
        video2_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/play.png"))); // NOI18N
        video2_button.setText("Ver video");
        video2_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                video2_buttonActionPerformed(evt);
            }
        });

        video3_button.setFont(new java.awt.Font("Merienda One", 0, 18)); // NOI18N
        video3_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/play.png"))); // NOI18N
        video3_button.setText("Ver video");
        video3_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                video3_buttonActionPerformed(evt);
            }
        });

        video4_button.setFont(new java.awt.Font("Merienda One", 0, 18)); // NOI18N
        video4_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/play.png"))); // NOI18N
        video4_button.setText("Ver video");
        video4_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                video4_buttonActionPerformed(evt);
            }
        });

        video1_button.setFont(new java.awt.Font("Merienda One", 0, 18)); // NOI18N
        video1_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/play.png"))); // NOI18N
        video1_button.setText("Ver video");
        video1_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                video1_buttonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Muli", 0, 18)); // NOI18N
        jLabel11.setText("Ejercicios para disminuir el estrés");

        video5_button.setFont(new java.awt.Font("Merienda One", 0, 18)); // NOI18N
        video5_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/play.png"))); // NOI18N
        video5_button.setText("Ver video");
        video5_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                video5_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(video5_button)
                    .addComponent(jLabel11)
                    .addComponent(video4_button)
                    .addComponent(video1_button)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(video2_button)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(video3_button)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(video1_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(video2_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(video3_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(video4_button)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(video5_button)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel2);

        tags.addTab("VIDEOS", jScrollPane2);

        home_button.setFont(new java.awt.Font("ABeeZee", 0, 14)); // NOI18N
        home_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        home_button.setText("Inicio");
        home_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_buttonActionPerformed(evt);
            }
        });

        audio_ok.setSelected(true);
        audio_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audio_okActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/audio (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 492, Short.MAX_VALUE)
                                .addComponent(audio_ok)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel10)
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fechaLB, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(horaLB, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(tags, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel8)))
                        .addContainerGap(35, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(home_button)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addComponent(audio_ok)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fechaLB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(horaLB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)))))
                .addGap(18, 18, 18)
                .addComponent(tags, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(home_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void home_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_buttonActionPerformed
        try {
            inicio();
        }
        catch (IOException ex) {
            Logger.getLogger(Recomendaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_home_buttonActionPerformed

    private void video1_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_video1_buttonActionPerformed
        video1();
    }//GEN-LAST:event_video1_buttonActionPerformed

    private void audio_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audio_okActionPerformed
        audioOk();
    }//GEN-LAST:event_audio_okActionPerformed

    private void video2_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_video2_buttonActionPerformed
        video2();
    }//GEN-LAST:event_video2_buttonActionPerformed

    private void video3_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_video3_buttonActionPerformed
        video3();
    }//GEN-LAST:event_video3_buttonActionPerformed

    private void video4_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_video4_buttonActionPerformed
        video4();
    }//GEN-LAST:event_video4_buttonActionPerformed

    private void video5_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_video5_buttonActionPerformed
        video5();
    }//GEN-LAST:event_video5_buttonActionPerformed

    public void audioOk()
    {
        /*if(audio_ok.isSelected())
        {
            AudioPlayer.player.start(audio);
        }
        if(!audio_ok.isSelected())
        {
            AudioPlayer.player.stop(audio);
        }*/
    }
    
    public JFrame getInicioForm() {
        return inicioForm;
    }

    public void setInicioForm(JFrame form) {
        this.inicioForm = form;
    }  
    
    public void inicio() throws IOException
    {
        //AudioPlayer.player.stop(audio);
        this.hide();
        Inicio inicio = new Inicio();
        inicio.setInicio(this);
        inicio.setVisible(true);
        inicio.setAutoRequestFocus(true);
        inicio.show(true);
        System.gc();        
        this.setVisible(false);
    }
    
    public void video1()
    {
        //AudioPlayer.player.stop(audio);
        Video1 video1 = new Video1();
        video1.setRecomendacionForm(this);
        video1.setAutoRequestFocus(true);
        video1.show(true);
        System.gc();        
        this.setVisible(false);
    }
    
    public void video2()
    {
        //AudioPlayer.player.stop(audio);
        Video2 video2 = new Video2();
        video2.setRecomendacionForm(this);
        video2.setAutoRequestFocus(true);
        video2.show(true);
        this.setVisible(false);
        System.gc();
    }
    
    public void video3()
    {
        //AudioPlayer.player.stop(audio);
        Video3 video3 = new Video3();
        video3.setRecomendacionForm(this);
        video3.setAutoRequestFocus(true);
        video3.show(true);
        this.setVisible(false);
        System.gc();
    }
    
    public void video4()
    {
        //AudioPlayer.player.stop(audio);
        Video4 video4 = new Video4();
        video4.setRecomendacionForm(this);
        video4.setAutoRequestFocus(true);
        video4.show(true);
        this.setVisible(false);
        System.gc();
    }
    
    public void video5()
    {
        //AudioPlayer.player.stop(audio);
        Video5 video5 = new Video5();
        video5.setRecomendacionForm(this);
        video5.setAutoRequestFocus(true);
        video5.show(true);
        this.setVisible(false);
        System.gc();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recomendaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recomendaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recomendaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recomendaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Recomendaciones().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Recomendaciones.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox audio_ok;
    private javax.swing.JTextPane estres_txPane;
    private javax.swing.JLabel fechaLB;
    private javax.swing.JButton home_button;
    private javax.swing.JLabel horaLB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane tags;
    private javax.swing.JButton video1_button;
    private javax.swing.JButton video2_button;
    private javax.swing.JButton video3_button;
    private javax.swing.JButton video4_button;
    private javax.swing.JButton video5_button;
    // End of variables declaration//GEN-END:variables
        
    @Override
    public void run() {
        Thread ct = Thread.currentThread();
        while (ct == hilo) {
            Reloj reloj = new Reloj();
            horaLB.setText(reloj.horaActual());
            
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            }
        }
    }
}

